server:
  port: 49030
spring:
  datasource:
    url: jdbc:mysql://101.43.145.108:3306/weather?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: weather
    password: l198923.
mybatis:
  type-aliases-package: com.liu.weathermail.entity
  configuration:
    cacheEnabled: false
    # 一定要设置，避免个别SQL执行时间过长，把系统搞跨
    default-statement-timeout: 5